component: kafka-producer
part-of: mosip-kafka
activeProfileEnv: default
exportLogs: enabled  # Let filebeat export the logs
probe:
  period: 30 # Seconds
  timeout: 5
  livenessPeriod: 10
  failureThreshold: 15
  startupPeriod: 10
  initialDelaySeconds: 120   # Seconds

sc:
  name: ""
pv:
  name: kafka-producer-pv
  size: 20Mi
pvc:
  name: kafka-producer-pvc
  size: 20Mi

nfs:
  server: {{ nfs.server }}
  path: {{nfs.folder}}/kafka-producer-tool

imagePullPolicy: Always

mountPath: /home/mosip/mnt      #path inside docker

docker:
  image: mosipdev/kafka-producer
  tag: latest
  ports:
    containerPort: 8080
    servicePort: 80

healthUrl: ''

logger_level: 'INFO'
bootstrap_servers: "kafka-0.kafka-headless.default.svc.cluster.local:9092,kafka-1.kafka-headless.default.svc.cluster.local:9092,kafka-2.kafka-headless.default.svc.cluster.local:9092"
output_topic: "manual-verification-bus-in"
src_path: '/home/mosip/mnt'
file_name: 'list_of_rids.csv'
message_bus_address: ""
src_type: "file"
url_path: ""
file_size_limit: "3000000"
thread_count: "10"

kafka:
  producer:
   name: kafka-producer
   dockerImage: mosipdev/kafka-producer:latest

